### ISSUE TITLE
logo design

### ISSUE THREAD

**Issue by batarian71** [antham/chyle#23]
Hi,

I want to make a contribution. Do you want me to design a logo for this repo? What do you think?

**Comment by antham** [comment]
Hi,
I would be more than pleased to welcome your contribution !

**Comment by batarian71** [comment]
hi again,

I designed a logo that emphasizes the function of the software. How do these look?

![chyle](https://user-images.githubusercontent.com/36008612/40880666-a88a2666-66bd-11e8-8c1a-4dc05f9796f4.jpg)

**Comment by antham** [comment]
The first one looks good to me

**Comment by batarian71** [comment]
I changed the font. I guess that looks better. If everything is ok I will send a pr.

![2](https://user-images.githubusercontent.com/36008612/40881103-b894e8d4-66c7-11e8-8dcd-dda315bc5a68.jpg)

**Comment by antham** [comment]
Yep that's better it's ok for me.

**Comment by batarian71** [comment]
could you check it please? https://github.com/antham/chyle/pull/24
